spring.application.name=backend_tableReservation
# Need on koostatud GPT abiga, sest endal H2 andmebaasiga kogemusi ei olnud.
spring.datasource.url=jdbc:h2:mem:restoranidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
